export const CATEGORIES_WITH_SUBS = {
  "Fashion": ["Streetwear", "Luxury", "Ethnic Wear", "Sustainable", "Mens Fashion", "Womens Fashion", "Kids"],
  "Beauty": ["Makeup", "Skincare", "Haircare", "Fragrance", "Nails", "K-Beauty"],
  "Technology": ["Smartphones", "Laptops", "Gaming", "Gadgets", "Coding", "AI"],
  "Food": ["Recipes", "Restaurants", "Street Food", "Healthy", "Baking", "Beverages"],
  "Travel": ["Budget", "Luxury", "Adventure", "Solo", "International", "Domestic", "Backpacking"],
  "Fitness & Health": ["Gym", "Yoga", "Calisthenics", "Running", "CrossFit", "Pilates"],
  "Comedy": ["Standup", "Skits", "Memes", "Parody", "Reactions"],
  "Lifestyle": ["Daily Vlogs", "Minimalism", "Productivity", "Home Decor"],
  "Finance & Investing": ["Stocks", "Crypto", "Personal Finance", "Startups", "Real Estate"],
  "Education": ["UPSC", "JEE/NEET", "Coding", "English Speaking", "Languages", "EdTech"],
  "Music": ["Singing", "Instrumental", "Hip-Hop", "Classical", "Independent"],
  "Art & Design": ["Painting", "Digital Art", "Photography", "Crafts", "Calligraphy"],
  "Parenting": ["Newborn", "Toddler", "Teen", "Mom Vlogs"],
  "Sports": ["Cricket", "Football", "Esports", "Athletics", "Combat"],
  "Gaming": ["BGMI", "Free Fire", "Valorant", "Minecraft", "Game Dev"],
  "Spiritual & Wellness": ["Yoga", "Meditation", "Devotional", "Astrology", "Mental Health", "Nutrition", "Sleep", "Self-care"],
  "Automotive": ["Cars", "Bikes", "EVs", "Reviews", "Auto Components"],
  "Books": ["Fiction", "Self-help", "Reviews", "Poetry"],
  "Real Estate": ["Commercial", "Residential", "Rentals", "PropTech"],
  "Business & Startups": ["Entrepreneurship", "Marketing", "SaaS", "E-commerce"],
  "Dance": ["Hip-hop", "Classical", "Contemporary", "Choreography"],
  "Entertainment": ["Movies", "TV Shows", "Web Series", "OTT", "Pop Culture", "Celebrity", "Films"],
  "FMCG": ["Personal Care", "Home Care", "Food & Beverages", "Packaged Goods"],
  "E-commerce & D2C": ["Apparel", "Electronics", "Groceries", "Marketplace"],
  "Healthcare & Pharma": ["Telemedicine", "Medical Devices", "Hospitals", "Pharmacies", "HealthTech"],
  "SaaS & B2B": ["Enterprise Software", "Cloud Services", "HR Tech", "CRM"],
  "Retail": ["Supermarkets", "Fashion Retail", "Consumer Electronics", "Luxury"],
  "Agriculture": ["AgriTech", "Farming", "Equipment", "Supply Chain"],
  "Telecommunications": ["Mobile Networks", "Broadband", "Telecom Equipment", "5G"],
  "Renewable Energy": ["Solar", "Wind", "EV Charging", "Green Tech"],
  "Media & Publications": ["News", "Magazines", "Digital Media", "Podcasts", "Journalism"],
  "Logistics & Supply Chain": ["Shipping", "Warehousing", "Delivery", "Supply Chain Management"],
  "Hospitality & Tourism": ["Hotels", "Airlines", "Travel Agencies", "Tourism Boards"],
  "Non-Profit & NGO": ["Charity", "Social Causes", "Environment", "Human Rights"],
  "Government & Public Sector": ["Public Services", "Infrastructure", "Defense", "Civic Tech"],
  "Events & Experiential": ["Concerts", "Conferences", "Exhibitions", "Event Management"],
  "Web3 & Crypto": ["Blockchain", "DeFi", "NFTs", "Metaverse", "Web3 Gaming"],
  "Pets & Animals": ["Pet Food", "Veterinary", "Pet Accessories", "Training"],
  "Home & Living": ["Furniture", "Appliances", "Gardening", "Smart Home"],
  "Toys & Hobbies": ["Board Games", "Action Figures", "Collectibles", "DIY Kits"]
};

export const APP_CATEGORIES = Object.keys(CATEGORIES_WITH_SUBS);
